# Generated by Django 2.0.4 on 2018-05-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('ROM', 'Romance'), ('THR', 'Thriller'), ('MYS', 'Mystery'), ('LIF', 'Life'), ('DRA', 'Drama'), ('HIS', 'Historic'), ('BIO', 'Biography'), ('KID', 'Kids')], default='ROM', max_length=3),
        ),
    ]
